List<String> suggestedLocations = [
  // Districts
  'Bagalkot',
  'Ballari ',
  'Bailhongal ',
  'Belagavi ',
  'Bengaluru Rural',
  'Bengaluru Urban',
  'Bidar',
  'Chamarajanagar',
  'Chikballapur',
  'Chikkamagaluru',
  'Chitradurga',
  'Dakshina Kannada',
  'Davanagere',
  'Dharwad',
  'Gadag',
  'Hassan',
  'Haveri',
  'Kalaburagi (Gulbarga)',
  'Kodagu',
  'Kolar',
  'Koppal',
  'Mandya',
  'Mysuru (Mysore)',
  'Raichur',
  'Ramanagara',
  'Shivamogga (Shimoga)',
  'Tumakuru (Tumkur)',
  'Udupi',
  'Uttara Kannada (Karwar)',
  'Vijayapura',
  'Yadgir',

  // Cities
  'Badami',
  'Bangarapet',
  'Bangalore',
  'Belgaum',
  'Bellary',
  'Bhadravati',
  'Bidar',
  'Bijapur',
  'Chikmagalur',
  'Chitradurga',
  'Davangere',
  'Gadag',
  'Gokak',
  'Gulbarga',
  'Hassan',
  'Hospet',
  'Hubli-Dharwad',
  'Kolar',
  'Madikeri',
  'Mandya',
  'Mangalore',
  'Manipal',
  'Mysore',
  'Raichur',
  'Ranebennur',
  'Shimoga',
  'Sirsi',
  'Tumkur',
  'Udupi',
  'Vijayapura',
  'Yadgir',
];
